// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojOZbc629JasXRjNUXlE2XNqd0S-m2uk',
    appId: '1:317912008960:web:e0123074ca336408220be5',
    messagingSenderId: '317912008960',
    projectId: 'cjeapp-9f94a',
    authDomain: 'cjeapp-9f94a.firebaseapp.com',
    storageBucket: 'cjeapp-9f94a.firebasestorage.app',
    measurementId: 'G-D8PP15S0XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhoA98z-PJdJ6ULVn2t02OfbIFadI6Cww',
    appId: '1:317912008960:android:f05a3d86d938a268220be5',
    messagingSenderId: '317912008960',
    projectId: 'cjeapp-9f94a',
    storageBucket: 'cjeapp-9f94a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5MfJkYgZ5FaFVUMotv-hTRWVgD031bA',
    appId: '1:317912008960:ios:ab7a5198eca39d0b220be5',
    messagingSenderId: '317912008960',
    projectId: 'cjeapp-9f94a',
    storageBucket: 'cjeapp-9f94a.firebasestorage.app',
    iosBundleId: 'com.chawla.cje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5MfJkYgZ5FaFVUMotv-hTRWVgD031bA',
    appId: '1:317912008960:ios:ab7a5198eca39d0b220be5',
    messagingSenderId: '317912008960',
    projectId: 'cjeapp-9f94a',
    storageBucket: 'cjeapp-9f94a.firebasestorage.app',
    iosBundleId: 'com.chawla.cje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCojOZbc629JasXRjNUXlE2XNqd0S-m2uk',
    appId: '1:317912008960:web:93171dea7a2a56c1220be5',
    messagingSenderId: '317912008960',
    projectId: 'cjeapp-9f94a',
    authDomain: 'cjeapp-9f94a.firebaseapp.com',
    storageBucket: 'cjeapp-9f94a.firebasestorage.app',
    measurementId: 'G-PPVPKYNYXJ',
  );
}
